import Head from "next/head";
import Image from "next/image";
import Profile from "@/src/components/profile/profile";
import List from "@/src/components/list/list";
import React from "react";
import Toogle from "@/src/components/button/toogleMode";
import Social from "@/src/components/social-links/social-links";

export default function Home() {
  return (
    <>
      <Head>
        <title>𝕰𝕾𝕮𝕷𝕰𝕽𝕺𝕾𝕰</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="container">
        <Profile />

        <Toogle />

        <List />

        <Social />
      </div>
    </>
  );
}
